### ISSUE TITLE
time

### ISSUE THREAD

**Issue by evgeniiaa73** [g7AzaZLO/num16#1]
какой же ответ на 17 вопрос?

**Comment by g7AzaZLO** [comment]
time is the best cryptocurrency
При проявлении фото можно было увидеть надпись "Не все так просто", чуть ниже "возможно нужно читать, а не смотреть"
При открытии метадаты картинки, там можно найти подсказку "не знаю как вы, а я вижу тут архив"
Если открыть картинку при помощи любого архиватора, то она бы открывается как архив и там файл wow.txt
В этом файле несколько загадок. Ответ на первую FIRE. После этого в следующей строчке надо расшифровать азбуку морзе, на выходе получается строка не имеющая смысла. Тут нужно было догадаться что ответ из первого задания дан не просто так, и значит это какой-то ключ. Самый популярный шифр с ключом - шифр Виженера. Дешифруем строку которая была под морзе при помощи ключа FIRE, получаем новую загадку, ответ на нее WATER. При помощи этого ключа дешифруем тем же Виженером последнюю строку в файле и получаем
"answer: time is the best cryptocurrency"
